# Generated by Django 3.2.3 on 2021-06-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210613_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(default='No Description', max_length=150),
        ),
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(default='No Title', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(default='no comment', max_length=256),
        ),
    ]
