# Generated by Django 3.2.3 on 2021-06-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210613_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(default='comment', max_length=256),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(default='Description', max_length=150),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(default='Title', max_length=50),
        ),
    ]
