# Generated by Django 3.2.3 on 2021-06-12 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bid_vlaue',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.bid'),
        ),
    ]
