# Generated by Django 3.2.3 on 2021-06-14 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_wishlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='Watchlist',
        ),
    ]
