# Generated by Django 3.2.3 on 2021-06-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20210616_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore')], default='FR', max_length=2),
        ),
    ]
