# Generated by Django 3.2.3 on 2021-06-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_listing_year_in_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('AT', 'Open'), ('CL', 'Close')], default='AT', max_length=2),
        ),
    ]
