# Generated by Django 3.2.3 on 2021-06-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20210616_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='win_status',
            field=models.CharField(choices=[('WN', 'WON'), ('LS', 'LOST'), ('PD', 'PENDING')], default='PD', max_length=2),
        ),
    ]
