# Generated by Django 3.2.3 on 2021-06-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_bid_win_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='catagory',
            field=models.CharField(choices=[('APP', 'Appliances'), ('APG', 'Apps & Games'), ('ACS', 'Arts, Crafts, & Sewing'), ('APA', 'Automotive Parts & Accessories'), ('BBY', 'Baby'), ('BPC', 'Beauty & Personal Care'), ('BKS', 'Books'), ('CVL', 'CDs & Vinyl'), ('CPA', 'Cell Phones & Accessories'), ('CSJ', 'Clothing, Shoes and Jewelry'), ('CFA', 'Collectibles & Fine Art'), ('CMP', 'Computers'), ('ELC', 'Electronics'), ('GDO', 'Garden & Outdoor'), ('GGF', 'Grocery & Gourmet Food'), ('HDW', 'Handmade'), ('HBC', 'Health, Household & Baby Care'), ('HMK', 'Home & Kitchen'), ('INS', 'Industrial & Scientific'), ('KND', 'Kindle'), ('LTG', 'Luggage & Travel Gear'), ('MTV', 'Movies & TV'), ('MIS', 'Musical Instruments'), ('OFP', 'Office Products'), ('PTS', 'Pet Supplies'), ('SPO', 'Sports & Outdoors'), ('THI', 'Tools & Home Improvement'), ('TYG', 'Toys & Games'), ('VIG', 'Video Games')], default='', max_length=3),
        ),
    ]
