# Generated by Django 4.2.8 on 2024-01-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_alter_listing_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(default='Description', max_length=1500),
        ),
    ]
